# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

# XXX: we need a real versioning and release workflow, not
# just hardcoding stuff here!

context:
  name: pinpointwcs2
  version: 0.9.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/WorldWideTelescope/pinpoint-wcs2/releases/download/v${{ version }}/pinpoint-wcs2-${{ version }}.tar.gz
  sha256: acf3973ef441d65d4da91cc496f87acd98dce42231c159568a74dd6d885e9c7d
  patches:
    # Since XMP-Toolkit-SDK is a git submodule and I would rather not maintain my
    # own fork of it, we patch it here instead of actually fixing the underlying code.
    - if: osx
      then:
        - apple-nothrow.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - ${{ compiler("cxx") }}
  host:
    - cfitsio
    - eigen
    - expat
    - if: linux
      then:
        - libgl-devel
    - qt-main
    - wcstools
    - xpa
    - zlib
  run:
    - ${{ pin_compatible("wcstools") }}

about:
  homepage: https://gitlab.com/WorldWideTelescope/pinpoint-wcs2
  repository: https://gitlab.com/WorldWideTelescope/pinpoint-wcs2
  license: GPL-3.0-or-later
  summary: Compute AVM/WCS for EPO images derived from FITS data
