# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

# XXX: we need a real versioning and release workflow, not
# just hardcoding stuff here!

context:
  name: pinpointwcs2
  version: 0.9.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/WorldWideTelescope/pinpoint-wcs2/releases/download/v${{ version }}/pinpoint-wcs2-${{ version }}.tar.gz
    sha256: b526303fb8262897abac8003242bba0acf5e5e1cc4108629c85b56b6061a1010

build:
  number: 0

requirements:
  build:
    - cmake
    - ${{ compiler("cxx") }}
  host:
    - cfitsio
    - eigen
    - expat
    - if: linux
      then:
        - libgl-devel
    - qt-main
    - wcstools
    - xpa
    - zlib
  run:
    - ${{ pin_compatible("wcstools") }}

about:
  homepage: https://gitlab.com/WorldWideTelescope/pinpoint-wcs2
  repository: https://gitlab.com/WorldWideTelescope/pinpoint-wcs2
  license: GPL-3.0-or-later
  summary: Compute AVM/WCS for EPO images derived from FITS data
