name: Build Conda Packages

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: macos-15-intel
            target-platform: osx-64
          - os: macos-latest
            target-platform: osx-arm64

    steps:
      - uses: actions/checkout@v6

      - name: Build a package
        uses: prefix-dev/rattler-build-action@v0.2.39
        with:
          upload-artifact: true
          artifact-name: package-${{ matrix.target-platform }}
          build-args: -c conda-forge -c pkgw-forge --target-platform ${{ matrix.target-platform }}
